Refactor NoMount patch application in build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -632,46 +632,6 @@ jobs:
             fi
           fi
           
-      - name: NoMount
-        if: ${{ inputs.add_nomount }}
-        run: |
-          echo ""
-          echo "=== NoMount patch ==="
-          cd "$KERNEL_ROOT/common" # cd "$CONFIG/common"
-          if [ "${{ inputs.cancel_susfs }}" == "true" ]; then
-            echo "  no susfs"
-            NOMOUNT_PATCH="nomount-kernel-5.10.patch"
-          else
-            echo "  with susfs"
-            NOMOUNT_PATCH="nomount-susfs-kernel-5.10.patch"
-          fi
-          curl -LSs "https://raw.githubusercontent.com/maxsteeel/nomount/refs/heads/master/patches/$NOMOUNT_PATCH" -o nomount.patch
-          chmod 777 nomount.patch
-          echo "Applying..."
-          patch -p1 < nomount.patch # > patch_nomount_log.txt 2>&1
-          #NOMOUNT_PATCH_EXIT_CODE=$?
-          #if [ $NOMOUNT_PATCH_EXIT_CODE -ne 0 ]; then
-          #  echo "ERROR nomount patch: $NOMOUNT_PATCH_EXIT_CODE"
-          #else
-          NAME_INFO="${{ env.NAME_INFO }}_NoMount"
-          echo "${{ inputs.ksu_variant }} NAME_INFO=$NAME_INFO"
-          echo "NAME_INFO=$NAME_INFO" >> $GITHUB_ENV
-          #fi
-          CONFIG_FILE="$DEFCONFIG"
-          echo "CONFIG_NOMOUNT=y" >> "$CONFIG_FILE"
-
-          NAME_INFO="_NoMount" # "${{ env.NAME_INFO }}"
-          if [ "${{ inputs.enable_susfs }}" == "true" ]; then NAME_INFO="${NAME_INFO}_uni"; fi
-          #if [ "${{ inputs.cancel_susfs }}" == "false" ]; then NAME_INFO="${NAME_INFO}_uni"; fi
-          if [ "${{ inputs.use_zram }}" == "true" ]; then NAME_INFO="${NAME_INFO}_zram"; fi
-          if [ "${{ inputs.use_bbg }}" == "true" ]; then NAME_INFO="${NAME_INFO}_bbg"; fi
-          if [ "${{ inputs.use_kpm }}" == "true" ]; then NAME_INFO="${NAME_INFO}_kpm"; fi
-          #if [ "${{ inputs.enable_tmpfs }}" == "true" ]; then NAME_INFO="${NAME_INFO}_tmpfs"; fi
-          if [ "${{ inputs.enable_susfs }}" == "true" ]; then NAME_INFO="${NAME_INFO}_tmpfs"; fi
-          if [ "${{ inputs.enable_susfs }}" == "true" ]; then NAME_INFO="${NAME_INFO}_susfs"; fi
-          echo "${{ inputs.ksu_variant }} NAME_INFO=$NAME_INFO"
-          echo "NAME_INFO=$NAME_INFO" >> $GITHUB_ENV
-
       # ==================== Unicode 绕过修复 ====================
       # 修复 Unicode 零宽字符绕过检测的问题
       - name: 应用 Unicode 绕过修复
@@ -719,6 +679,48 @@ jobs:
 
           cp $SUKISU_PATCHES/other/zram/zram_patch/${{ inputs.kernel_version }}/lz4k_oplus.patch ./
           patch -p1 -F 3 < lz4k_oplus.patch || true
+
+      - name: NoMount
+        if: ${{ inputs.add_nomount }}
+        working-directory: ${{ env.KERNEL_ROOT }}/common
+        run: |
+          echo ""
+          echo "=== NoMount patch ==="
+          ###########cd "$KERNEL_ROOT/common" # cd "$CONFIG/common"
+          if [ "${{ inputs.enable_susfs }}" == "false" ]; then
+            echo "  no susfs"
+            NOMOUNT_PATCH="nomount-kernel-5.10.patch"
+          else
+            echo "  with susfs"
+            NOMOUNT_PATCH="nomount-susfs-kernel-5.10.patch"
+          fi
+          curl -LSs "https://raw.githubusercontent.com/maxsteeel/nomount/refs/heads/master/patches/$NOMOUNT_PATCH" -o nomount.patch
+          chmod 777 nomount.patch
+          echo "Applying..."
+          patch -p1 < nomount.patch # > patch_nomount_log.txt 2>&1          
+          #NOMOUNT_PATCH_EXIT_CODE=$?
+          echo "=== END NoMount patch ==="
+          #if [ $NOMOUNT_PATCH_EXIT_CODE -ne 0 ]; then
+          #  echo "ERROR nomount patch: $NOMOUNT_PATCH_EXIT_CODE"
+          #else
+          NAME_INFO="${{ env.NAME_INFO }}_NoMount"
+          echo "${{ inputs.ksu_variant }} NAME_INFO=$NAME_INFO"
+          echo "NAME_INFO=$NAME_INFO" >> $GITHUB_ENV
+          #fi
+          CONFIG_FILE="$DEFCONFIG"
+          echo "CONFIG_NOMOUNT=y" >> "$CONFIG_FILE"
+
+          NAME_INFO="_NoMount" # "${{ env.NAME_INFO }}"
+          #if [ "${{ inputs.bypass_unicode }}" == "true" ]; then NAME_INFO="${NAME_INFO}_uni"; fi
+          if [ "${{ inputs.enable_susfs }}" == "true" ]; then NAME_INFO="${NAME_INFO}_uni"; fi
+          if [ "${{ inputs.use_zram }}" == "true" ]; then NAME_INFO="${NAME_INFO}_zram"; fi
+          if [ "${{ inputs.use_bbg }}" == "true" ]; then NAME_INFO="${NAME_INFO}_bbg"; fi
+          if [ "${{ inputs.use_kpm }}" == "true" ]; then NAME_INFO="${NAME_INFO}_kpm"; fi
+          #if [ "${{ inputs.enable_tmpfs }}" == "true" ]; then NAME_INFO="${NAME_INFO}_tmpfs"; fi
+          NAME_INFO="${NAME_INFO}_tmpfs"
+          if [ "${{ inputs.enable_susfs }}" == "true" ]; then NAME_INFO="${NAME_INFO}_susfs"; fi
+          echo "${{ inputs.ksu_variant }} NAME_INFO=$NAME_INFO"
+          echo "NAME_INFO=$NAME_INFO" >> $GITHUB_ENV
 
       # ==================== 修复三星 6.6 WiFi/蓝牙 ====================
       # 添加三星设备所需的 KDP 符号
