Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -65,6 +65,18 @@ on:
         required: false
         type: boolean
         default: false
+      add_nomount:
+        required: false
+        type: boolean
+        default: false
+      add_nomountX:
+        required: false
+        type: boolean
+        default: false
+      add_hymofs:
+        required: false
+        type: boolean
+        default: false
 
 jobs:
   build-kernel:
@@ -589,6 +601,151 @@ jobs:
             fi
           fi
 
+      - name: Enable manual_hook when disabling SUSFS (strictly checked version)
+        if: ( !inputs.enable_susfs ) && ( inputs.ksu_variant == 'ReSukiSU' )
+        run: |
+          cd $KERNEL_ROOT/common # cd "$CONFIG/common"
+          echo "正在应用 Manual Hook 补丁"
+
+          PATCH="$GITHUB_WORKSPACE/patches/resukisu_manual_hooks.patch"
+
+          # 检查文件是否存在
+          if [ ! -f "$PATCH" ]; then
+              echo "Patch file not found: $PATCH"
+              exit 1
+          fi
+
+          # 执行 Patch 并捕获所有输出
+          set +e
+
+          echo "Executing patch 命令..."
+
+          patch -p1 -F 3 --fuzz=5 < "$PATCH" > patch_log.txt 2>&1
+
+          # 记录 patch 命令本身的退出代码
+          PATCH_EXIT_CODE=$?
+
+          set -e
+
+          # 显示完整日志
+          echo "====================== PATCH OUTPUT START ======================"
+          if [ -f patch_log.txt ]; then
+              cat patch_log.txt
+          else
+              echo "无日志输出"
+          fi
+          echo "====================== PATCH OUTPUT END   ======================"
+
+          if [ $PATCH_EXIT_CODE -ne 0 ]; then
+              echo "Patch The command returned an error code. ($PATCH_EXIT_CODE)"
+              exit 1
+          elif grep -qi "FAILED" patch_log.txt; then
+              echo "检测到 Hunk FAILED (补丁未能应用)"
+              exit 1
+          elif grep -qi "malformed" patch_log.txt; then
+              echo "检测到 malformed patch (补丁格式/行号/空行错误)"
+              exit 1
+          elif grep -qi "unexpected end" patch_log.txt; then
+              echo "检测到 unexpected end (补丁文件可能不完整)"
+              exit 1
+          else
+              echo "Manual Hook 补丁已成功应用"
+          fi
+
+      - name: NoMount
+        if: inputs.add_nomount || inputs.add_nomountX
+        working-directory: ${{ env.KERNEL_ROOT }}/common
+        run: |
+          echo ""
+          echo "=== NoMount patch ==="
+          ###########cd "$KERNEL_ROOT/common" # cd "$CONFIG/common"
+          if [ "${{ inputs.enable_susfs }}" == "false" ]; then            
+            NOMOUNT_PATCH="nomount-kernel-${{ inputs.kernel_version }}.patch"
+            echo "  no susfs: $NOMOUNT_PATCH"
+          else            
+            NOMOUNT_PATCH="nomount-susfs-kernel-${{ inputs.kernel_version }}.patch"
+            echo "  with susfs: $NOMOUNT_PATCH"
+          fi
+          if [ "${{ inputs.add_nomountX }}" == "true" ]; then
+            IS_X="X"
+            echo "  <> saved/working patch"
+            cp "$GITHUB_WORKSPACE/patches/nomount/$NOMOUNT_PATCH" nomount.patch
+          else
+            IS_X=""
+            MASTER_EXP="staging" # master experimental staging
+            echo "  <> ORIGinal/latest patch ($MASTER_EXP)"
+            curl -LSs "https://raw.githubusercontent.com/maxsteeel/nomount/refs/heads/$MASTER_EXP/patches/$NOMOUNT_PATCH" -o nomount.patch
+          fi
+          chmod 777 nomount.patch
+          echo "Applying..."
+          patch -p1 --fuzz=10 < nomount.patch # > patch_nomount_log.txt 2>&1          
+          #NOMOUNT_PATCH_EXIT_CODE=$?
+          echo "=== END NoMount patch ==="
+          #if [ $NOMOUNT_PATCH_EXIT_CODE -ne 0 ]; then
+          #  echo "ERROR nomount patch: $NOMOUNT_PATCH_EXIT_CODE"
+          #else
+          NAME_INFO="${{ env.NAME_INFO }}_NoMount$IS_X"
+          echo "${{ inputs.ksu_variant }} NAME_INFO=$NAME_INFO"
+          echo "NAME_INFO=$NAME_INFO" >> $GITHUB_ENV
+          #fi
+
+      - name: HymoFS support
+        if: ${{ inputs.add_hymofs }}
+        working-directory: ${{ env.KERNEL_ROOT }}/common
+        run: |
+          echo "[💠] Apply HymoFS"
+          #########cd "$CONFIG/common" # cd $KERNEL_DIR 
+
+          # HymoFS One-Line Setup Script
+          # Usage: curl -LSs https://raw.githubusercontent.com/Anatdx/HymoFS/main/setup.sh | bash -s defconfig arch/arm64/configs/gki_defconfig with-susfs
+
+          if [ "${{ inputs.enable_susfs }}" == "false" ]; then 
+            curl -LSs https://raw.githubusercontent.com/Anatdx/HymoFS/main/setup.sh | bash -s defconfig arch/arm64/configs/gki_defconfig
+          else
+            curl -LSs https://raw.githubusercontent.com/Anatdx/HymoFS/main/setup.sh | bash -s defconfig arch/arm64/configs/gki_defconfig
+          fi          
+          #patch -p1 --fuzz=3 < hymofs.patch # patch -p1 --fuzz=3 < hymofs.patch
+          
+          NAME_INFO="${{ env.NAME_INFO }}_hymofs"
+          echo "@@@@@@@@@@@@@@@@@@@ NAME_INFO=$NAME_INFO"
+          echo "NAME_INFO=$NAME_INFO" >> $GITHUB_ENV
+
+          echo "[✅] Done."
+
+      - name: Config Options And NAME_INFO
+        run: |
+          NAME_INFO="${{ env.NAME_INFO }}"
+          #if [ "${{ inputs.bypass_unicode }}" == "true" ]; then NAME_INFO="${NAME_INFO}_uni"; fi
+          if [ "${{ inputs.enable_susfs }}" == "true" ]; then NAME_INFO="${NAME_INFO}_uni"; fi
+          if [ "${{ inputs.use_zram }}" == "true" ]; then NAME_INFO="${NAME_INFO}_zram"; fi
+          if [ "${{ inputs.use_bbg }}" == "true" ]; then NAME_INFO="${NAME_INFO}_bbg"; fi
+          if [ "${{ inputs.use_kpm }}" == "true" ]; then NAME_INFO="${NAME_INFO}_kpm"; fi
+          #if [ "${{ inputs.enable_tmpfs }}" == "true" ]; then NAME_INFO="${NAME_INFO}_tmpfs"; fi
+          NAME_INFO="${NAME_INFO}_tmpfs"
+          if [ "${{ inputs.enable_susfs }}" == "true" ]; then NAME_INFO="${NAME_INFO}_susfs"; fi
+          echo "${{ inputs.ksu_variant }} NAME_INFO=$NAME_INFO"
+          echo "NAME_INFO=$NAME_INFO" >> $GITHUB_ENV
+
+          if [[ "${{ inputs.add_nomount }}" == "true" ]] || [[ "${{ inputs.add_nomountX }}" == "true" ]]; then
+            #echo "CONFIG_NOMOUNT=y" >> "${{ env.DEFCONFIG_FRAGMENT }}"
+            CONFIG_FILE="$DEFCONFIG"
+            echo "CONFIG_NOMOUNT=y" >> "$CONFIG_FILE"
+          fi
+
+          if [[ "${{ inputs.add_hymofs }}" == "true" ]]; then
+            CONFIG_FILE="$DEFCONFIG"
+            echo "CONFIG_HYMOFS=y" >> "$CONFIG_FILE"
+            echo "CONFIG_HYMOFS_REVERSE_LOOKUP=y" >> "$CONFIG_FILE"
+            echo "CONFIG_HYMOFS_FORWARD_REDIRECT=y" >> "$CONFIG_FILE"
+            echo "CONFIG_HYMOFS_HIDE_ENTRIES=y" >> "$CONFIG_FILE"
+            echo "CONFIG_HYMOFS_INJECT_ENTRIES=y" >> "$CONFIG_FILE"
+            echo "CONFIG_HYMOFS_STAT_SPOOF=y" >> "$CONFIG_FILE"
+            echo "CONFIG_HYMOFS_XATTR_FILTER=y" >> "$CONFIG_FILE"
+            echo "CONFIG_HYMOFS_UNAME_SPOOF=y" >> "$CONFIG_FILE"
+            echo "CONFIG_HYMOFS_CMDLINE_SPOOF=y" >> "$CONFIG_FILE"
+            echo "CONFIG_HYMOFS_DEBUG=y" >> "$CONFIG_FILE"
+          fi
+
       # ==================== Unicode 绕过修复 ====================
       # 修复 Unicode 零宽字符绕过检测的问题
       - name: 应用 Unicode 绕过修复
@@ -875,7 +1032,7 @@ jobs:
       - name: 创建 AnyKernel3 压缩包
         run: |
           cd $ANYKERNEL3
-          ZIP_NAME="${{ inputs.android_version }}-${{ inputs.kernel_version }}.${{ inputs.sub_level }}-${{ inputs.os_patch_level }}-AnyKernel3.zip"
+          ZIP_NAME="${{ inputs.android_version }}-${{ inputs.kernel_version }}.${{ inputs.sub_level }}-${{ inputs.os_patch_level }}${{ env.NAME_INFO }}-AnyKernel3.zip"
           mv ../Image ./Image
           zip -r "../$ZIP_NAME" ./*
 
@@ -903,7 +1060,7 @@ jobs:
           # 创建普通 boot.img
           $MKBOOTIMG --header_version 4 --kernel Image --output boot.img --ramdisk out/ramdisk --os_version 12.0.0 --os_patch_level "${{ inputs.os_patch_level }}"
           $AVBTOOL add_hash_footer --partition_name boot --partition_size $((64 * 1024 * 1024)) --image boot.img --algorithm SHA256_RSA2048 --key $BOOT_SIGN_KEY_PATH
-          cp ./boot.img ../${{ inputs.android_version }}-${{ inputs.kernel_version }}.${{ inputs.sub_level }}-${{ inputs.os_patch_level }}-boot.img
+          cp ./boot.img ../${{ inputs.android_version }}-${{ inputs.kernel_version }}.${{ inputs.sub_level }}-${{ inputs.os_patch_level }}${{ env.NAME_INFO }}-boot.img
 
           # 创建 gzip 压缩的 boot.img
           $MKBOOTIMG --header_version 4 --kernel Image.gz --output boot-gz.img --ramdisk out/ramdisk --os_version 12.0.0 --os_patch_level "${{ inputs.os_patch_level }}"
@@ -970,7 +1127,7 @@ jobs:
       - name: 上传构建产物
         uses: actions/upload-artifact@v4
         with:
-          name: ${{ inputs.ksu_variant }}_kernel-${{ env.CONFIG }}
+          name: ${{ inputs.ksu_variant }}_kernel-${{ env.CONFIG }}${{ env.NAME_INFO }}
           path: |
             *AnyKernel3.zip
             *.img
